import React from 'react'
import Head from 'next/head'

export default function PokemonLayout(props) {
  const {children} =  props
  return (
    <div>
      <Head>
        <title>Pokedex by Abraham</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <main 
        css={{
          oberflow: 'hidden',
          height: '100vh',
          backgroundColor: '#00041F'
        }}
      >
        <div css={{
          position: 'fixed', 
          backgroundColor: '#db504a', 
          width: '100%', 
          paddingLeft: '24px', 
          display: 'flex', 
          alignItems: 'center', 
          justifyContent: 'center', 
          borderRadius: '0px 0px 10px 10px', 
          fontFamily: "'PokemonSolid'", 
          color: '#ffde5a', 
          WebkitTextStroke: '1px black'}}>
          <h2 css={{
            width: 'fit-content', 
            margin: 0
          }}>
            Pokedex <sub css={{fontSize: '10pt'}}>by Abraham</sub></h2>
        </div>
        {children}
      </main>
    </div>
  )
}
